apiVersion: v1
kind: Service
metadata:
  name: usermng-travisci-heroku-service
spec:
  type: NodePort
  selector:
    app: usermng-travisci-heroku
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001